name: Auto Sync New Movies

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
    inputs:
      source:
        description: 'কোন ওয়েবসাইট থেকে কনটেন্ট আনবেন?'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - cinefreak
          - hdmovie2

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Tools
        run: npm install axios cheerio firebase-admin

      - name: Run Auto Scraper
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          SOURCE_CHOICE: ${{ github.event.inputs.source || 'both' }}
        run: node scraper.js
